// Code generated by mockery v1.0.0. DO NOT EDIT.
package mocks

import context "context"
import inventar "github.com/West-Labs/inventar"
import mock "github.com/stretchr/testify/mock"

// UserRepository is an autogenerated mock type for the UserRepository type
type UserRepository struct {
	mock.Mock
}

// GetByUsername provides a mock function with given fields: ctx, username
func (_m *UserRepository) GetByUsername(ctx context.Context, username string) (*inventar.Credential, error) {
	ret := _m.Called(ctx, username)

	var r0 *inventar.Credential
	if rf, ok := ret.Get(0).(func(context.Context, string) *inventar.Credential); ok {
		r0 = rf(ctx, username)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*inventar.Credential)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, username)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Signup provides a mock function with given fields: ctx, credential
func (_m *UserRepository) Signup(ctx context.Context, credential *inventar.Credential) (bool, error) {
	ret := _m.Called(ctx, credential)

	var r0 bool
	if rf, ok := ret.Get(0).(func(context.Context, *inventar.Credential) bool); ok {
		r0 = rf(ctx, credential)
	} else {
		r0 = ret.Get(0).(bool)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *inventar.Credential) error); ok {
		r1 = rf(ctx, credential)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
